# Generated by Django 3.2.8 on 2021-10-22 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Car Type',
                'verbose_name_plural': 'Car Types',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=64)),
                ('doc', models.CharField(max_length=15)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=1)),
                ('short', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Document Type',
                'verbose_name_plural': 'Document Types',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RevisionType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Revision Type',
                'verbose_name_plural': 'Revision Type',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('registered_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('hour', models.TimeField()),
                ('plate', models.CharField(max_length=6)),
                ('ended', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('car_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.cartype')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='r_as_driver', to='api.client')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='r_as_owner', to='api.client')),
                ('rev_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.revisiontype')),
            ],
            options={
                'verbose_name': 'Reserv',
                'verbose_name_plural': 'Reserves',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='doc_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.doctype'),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('doc_type', 'doc')},
        ),
    ]
