# Generated by Django 3.2.8 on 2021-10-16 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('registered_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('hour', models.TimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('plate', models.CharField(max_length=6)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='r_as_driver', to='api.client')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='r_as_owner', to='api.client')),
            ],
            options={
                'verbose_name': 'Reserv',
                'verbose_name_plural': 'Reserves',
                'ordering': ['id'],
            },
        ),
    ]
