# Generated by Django 2.2.24 on 2021-09-24 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=1)),
                ('short', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Document Type',
                'verbose_name_plural': 'Document Types',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=64)),
                ('doc', models.CharField(max_length=15)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('doc_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.DocType')),
            ],
            options={
                'unique_together': {('doc_type', 'doc')},
            },
        ),
    ]
